### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/Treats-Sweet-Shop#1]
As a **User** I can easily navigate around the site so that I can **view different pages and sections on the site**

# Acceptance  Criteria 
- Acceptance Criteria 1: Have a top Navigation bar
- Acceptance Criteria 2:  Each navigation link takes the user to the desired page.

# Tasks
- [x] Design the Nav bar
- [x] Use bootstrap to create the Nav bar
- [x] Make sure Nav bar is easily visible to user and clear
- [x] navigation bar changes to a burger menu when on smaller devices
