### ISSUE TITLE
USER STORY: Register as a New User

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/Treats-Sweet-Shop#2]
As a **User** I can **Register an account** so that I can use the **full functionality of the site**

# Acceptance  Criteria 
- Acceptance  Criteria 1:  A registration page where the user can sign up
- Acceptance  Criteria 2: Check if the account is already registered before allowing a user to sign up

# Tasks
- [x] Add HTML from as a registration page on the site, where the user can sign up.
- [x] Verify all data entered into the form
- [x] Verify the account does not already exist
- [x] Add the user to the database
