### ISSUE TITLE
USER STORY: Add a new Product

### ISSUE THREAD

**Issue by kpsdev1** [kpsdev1/Treats-Sweet-Shop#6]
As a **Superuser** I can **add a new product** so that **I can sell them on the site**

# Acceptance  Criteria 
- Acceptance  Criteria 1: When logged in as a superuser, have a button to add a product
- Acceptance  Criteria 2: Once added the Product will display in the list of products

# Tasks
- [x] Check to make sure the user is logged in
- [x] Create a form that allows the user to enter the product details
- [x] Display the new product after the user clicks submit
